GET http://127.0.0.1:8000/api/diets
Authorization: Bearer seu_token_aqui


###
POST http://127.0.0.1:8000/api/diet
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}