### 
POST http://127.0.0.1:8000/api/register
Content-Type: application/json
Accept: application/json

{
  "name": "teste",
  "email": "teste@gmail.com",
  "password": "senha123",
  "phone": "11999999999",
  "password_confirmation": "senha123"
}

###
POST http://127.0.0.1:8000/api/login
Content-Type: application/json
Accept: application/json

{
  "email": "teste@gmail.com",
  "password": "senha123"
}

###
GET http://127.0.0.1:8000/api/diets
Authorization: Bearer 1|sqFA4FmbvJr4jAf03Yq2LBG1l9WyQSRFrkv4SNC460a936fd
